### ISSUE TITLE
Fixed Materials

### ISSUE THREAD

**Issue by x-channel** [vnen/godot-portugues#6]
http://godotengine.org/projects/godot-engine/wiki/Fixed_Materials

PelamordeDeus. Alguém sugere uma boa tradução para esse título que não seja Materiais Reparados, nem Materiais Fixos.

**Comment by vnen** [comment]
Boa pergunta. Mas o que é um "Fixed Material"? Parece que só a Godot usa esse nome.

**Comment by marcosbitetti** [comment]
Creio que o fixed vem do fato do material estar embutido na própria engine. Vc pode usar a palavra "embutido", "nativo",... ou talvez melhor, "pré-definido"

**Comment by x-channel** [comment]
@vnen eu encontrei outras coisas sobre fixed, mas não fizeram muito sentido, eles se referem a isso de uma forma antiga. OpenGL 1.5 e DirectX 7. O que não faz sentido na tradução.

@marcosbitetti gostei do nome. "Nativo". Acho que se encaixa bem.

**Comment by x-channel** [comment]
Falta pouca coisa nesse, mas vou fazer amanhã, enquanto passo para outro
