### ISSUE TITLE
Creating 2d Games

### ISSUE THREAD

**Issue by relsi** [vnen/godot-portugues#9]

**Comment by vnen** [comment]
@relsi você abriu quatro traduções de uma vez, tem alguma previsão? Tem gente traduzindo direto no site, então veja se já não foi feito antes de começar cada página :wink:.

**Comment by relsi** [comment]
@vnen Devo finalizar até amanhã. Achei que o pessoal estava se guiando por aqui para começar as traduções, por isso nem olhei a página.

**Comment by vnen** [comment]
Traduzido: http://www.godotengine.org/projects/godot-engine-em-portugues/wiki/Criando_Jogos_2D
